baseURL: "https://harryli.netlify.app/"
title: Harry Li
theme: "hugo-PaperMod"
languageCode: en-us

ignoreFiles:
  - "/post/Imperial"

menu:
  main:
    - name: Blog
      url: "/blog"
    - name: About
      url: "/about"
    - name: Research
      url: "/research"
    - name: Search
      url: "/search"

params:
    profileMode:
        enabled: true
        subtitle: "Personal website"
        imageUrl: "avatar.png"
        imageTitle: "profile picture"
        imageWidth: 250 # custom size
        imageHeight: 250 # custom size
        buttons:
            - name: About
              url: "/about"        
            - name: Blog
              url: "/blog"
    socialIcons:
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/harryxcli/"
        - name: Github
          url: "https://github.com/HarryLi98/"
    comments: false

disqusShortname: Harry

outputs:
    home:
        - HTML
        - RSS
        - JSON
