baseURL: "https://harryli.netlify.app/"
title: Harry Li
theme: "hugo-PaperMod"
languageCode: en-us

ignoreFiles:
  - "/post/Imperial"

menu:
  main:
    - name: Blog
      url: "/blog"
    - name: About
      url: "/about"
    - name: Research
      url: "/research"
    - name: Search
      url: "/search"

params:
    profileMode:
        enabled: true
        subtitle: "Personal website"
        imageUrl: "avatar.png"
        imageTitle: "profile picture"
        imageWidth: 250 # custom size
        imageHeight: 250 # custom size
        buttons:
            - name: About
              url: "/about"        
            - name: Blog
              url: "/blog"
            - name: CV
              url: "/post/About/public.pdf"
    socialIcons:
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/harryxcli/"
        - name: "GitHub"
          url: "https://github.com/HarryLi98/"
    comments:
      provider: giscus
      commentable:
        page: false
        post: true
        docs: false
        project: false
        publication: true
        talk: false
      giscus:
        repo: "HarryLi98/harryli98.github.io"
        repo_id: "R_kgDOIonjdg"
        category: "Announcements"
        category_id: "DIC_kwDOIonjds4CZ7AN"
        mapping: "pathname"
        label: "comment"
        input_position: "top"
        theme: "dark_dimmed"
        reactions_enabled: 1
        data_lang: "en"

outputs:
    home:
        - HTML
        - RSS
        - JSON
