---
title: "My review of the MSc Applied Mathematics at Imperial"
author: "Harry Li"
date: 2024-02-28
tags: ["Imperial", "Maths", "Life"]
ShowToc: true
---

# Introduction


I started studying part-time for a Master's in Applied Mathematics at Imperial in October 2021, while continuing to work at 80% capacity at the Bank of England.

# Motivation
I had only recently graduated from a Master's in Econometrics and Mathematical Economics from The London School of Economics in summer 2020, and doing another Master's was the last thing on my mind. However, the Bank encourages new graduates to en-roll in some part-time study program, which they support by providing some study leave. I've always enjoyed studying maths, and saw this as an opportunity to improve my technical skills. I wanted to learn about partial differential equations and machine learning in order to apply these skills to solve problems in economics.

Therefore, it was great when I learnt that Imperial offers students to study for a postgraduate degree in Maths part-time. Imperial was my top choice as it has an excellent maths department, is based in London, and was one of the only universities which accommodated part-time study. Thankfully they accepted my application, despite me not meeting their entry requirements of an undergraduate degree in maths, physics or engineering.

I must admit I was initially apprehensive about enrolling for this Master's. Some of my friends studied maths at Imperial and warned me that the workload was intense. I wasn't sure if I would be able to juggle a part-time Master's while still working full-time four days a week. Furthermore, I was worried that I would struggle to understand lectures as I didn't have an undergraduate degree in maths.

My first year at Imperial was mixed. There wasn't much of an induction and lectures started in the first week. In the first term, I studied Introduction to Partial Differential Equations and Dynamics of Learning and Iterated Games. 

COVID meant that Imperial adopted a hybrid teaching style, which meant that lectures were pre-recorded to be watched on-line in your own time, and classes were hybrid, meaning that you could attend in-person or dial-in on Teams. The way it worked was that lecturers released weekly recordings, which were to be watched before the classes. All of the modules used the same lecture recordings they made during the 2020 academic year. I must admit it felt a bit like learning from YouTube. Some lecture recordings were low quality, as they re-used recordings from pre-COVID where the white board the lecturer was writing on was barely visible. Often, the lecturer and class teacher were different, with the lecturer being MIA for the term, making it more difficult to ask questions.

## Modules

### Theory of Partial Differential Equations

### Dynamics of Learning and Iterated Games
No prior knowledge was really needed for this module.

### Methods for Data Science
Personally I really enjoyed how this module integrated machine learning theory with its implementation in Python. We covered all the classical machine learning methods like Ridge and Lasso regression, Random Forests, Support Vector Machines, but also deep neural networks and its implementation in TensorFlow. This module was fully coursework assessed. The algorithms from scratch in Python, which gave me a deeper understanding.

Prior knowledge of multivariate calculus were useful for this module.

### Introduction to Statistical Learning
This module covered more of the theory behind machine learning.
